/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package hmlfotofissa;

import java.awt.image.BufferedImage;

/**
 *
 * @author Chris
 */
public class fotoView extends javax.swing.JPanel {

    /**
     * Creates new form fotoView
     */
    private BufferedImage oldP;
    private BufferedImage newP;
    private String name;
    private boolean isset = false;
    
    public fotoView(BufferedImage oldP, BufferedImage newP, String name) {
        initComponents();
        this.oldP = oldP;
        this.newP = newP;
        this.name = name;
        jPanel1.setSize(100, 100);
        jPanel1.setVisible(true);
        jPanel2.setVisible(true);
    }
    public void paintPictures(){
        
        
    }
    public void blackOut(boolean state){
        jPanel1.setVisible(state);
        jPanel2.setVisible(state);
        naam.setVisible(state);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        naam = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(0, 0, 0));

        naam.setBackground(new java.awt.Color(0, 0, 0));
        naam.setFont(new java.awt.Font("Copse", 0, 72)); // NOI18N
        naam.setForeground(new java.awt.Color(255, 255, 255));
        naam.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setFocusable(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(136, 220));
        jPanel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jPanel1ComponentResized(evt);
            }
        });
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(naam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
                        .addGap(175, 175, 175)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)))
                .addGap(175, 175, 175))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 727, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(naam, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel1ComponentResized
    if(!isset){    
        if(oldP!=null){
            setVisible(true);
            repaint();
            int w = jPanel1.getWidth();
            int h = jPanel1.getHeight();
            Foto links = new Foto(oldP, w, h);
            jPanel1.removeAll();
            jPanel1.add(links);
            jPanel1.validate();
            jPanel1.updateUI();
        }
        if(newP!=null){
            int w = jPanel2.getWidth();
            int h = jPanel2.getHeight();
            Foto rechts = new Foto(newP, w, h);
            jPanel2.removeAll();
            jPanel2.add(rechts);
            jPanel2.validate();
            jPanel2.updateUI();
        }
        if(name!=null){
            naam.setText(name);
        }
        validate();
        updateUI();
        //isset = true;
    }
    }//GEN-LAST:event_jPanel1ComponentResized


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel naam;
    // End of variables declaration//GEN-END:variables
}
